name: mRNA_circRNA_quant
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - bcrypt=3.1.7
  - bowtie2=2.3.5.1
  - bwa=0.7.17
  - bzip2=1.0.8
  - c-ares=1.18.1
  - ca-certificates=2021.10.8
  - certifi=2019.11.28
  - cffi=1.14.0
  - cryptography=2.8
  - enum34=1.1.10
  - htslib=1.15
  - idna=3.1
  - ipaddress=1.0.23
  - keyutils=1.6.1
  - krb5=1.19.3
  - ld_impl_linux-64=2.36.1
  - libblas=3.9.0
  - libcblas=3.9.0
  - libcurl=7.82.0
  - libdeflate=1.10
  - libedit=3.1.20191231
  - libev=4.33
  - libffi=3.2.1
  - libgcc-ng=11.2.0
  - libgfortran-ng=11.2.0
  - libgfortran5=11.2.0
  - libgomp=11.2.0
  - liblapack=3.9.0
  - libnghttp2=1.47.0
  - libnsl=2.0.0
  - libopenblas=0.3.18
  - libssh2=1.10.0
  - libstdcxx-ng=11.2.0
  - libzlib=1.2.11
  - ncurses=6.3
  - numpy=1.16.5
  - openssl=1.1.1l
  - paramiko=2.7.2
  - pathlib2=2.3.5
  - perl=5.32.1
  - pip=20.1.1
  - plumbum=1.7.2
  - pycparser=2.21
  - pynacl=1.3.0
  - pysam=0.18.0
  - python=2.7
  - python_abi=2.7
  - readline=8.1
  - samtools=1.15
  - scandir=1.10.0
  - setuptools=44.0.0
  - six=1.16.0
  - sqlite=3.37.1
  - star=2.7.10a
  - subread=2.0.1
  - tk=8.6.12
  - wheel=0.37.1
  - xz=5.2.5
  - zlib=1.2.11

